# Generated by Django 6.0.3 on 2026-03-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='mentors/'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
