# Generated by Django 6.0.3 on 2026-03-16 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auction_is_active_auction_title_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.auction'),
        ),
    ]
